project_id = "gqnvkecmxjijrxhggcro"

[functions.send-contact-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.change-password]
verify_jwt = true

[functions.check-rate-limit]
verify_jwt = false

[functions.shopify-oauth-start]
verify_jwt = false

[functions.shopify-oauth-callback]
verify_jwt = false

[functions.shopify-sync-products]
verify_jwt = true

[functions.shopify-enable-auto-sync]
verify_jwt = true

[functions.shopify-webhook-handler]
verify_jwt = false

[functions.shopify-test-connection]
verify_jwt = true

[functions.shopify-disconnect-store]
verify_jwt = true

[functions.shopify-sync-inventory]
verify_jwt = true

[functions.shopify-sync-orders]
verify_jwt = true

[functions.shopify-register-webhook]
verify_jwt = true

[functions.shopify-buy-label]
verify_jwt = true

[functions.shopify-auto-sync]
verify_jwt = false

[[functions.shopify-auto-sync.schedule]]
cron = "0 * * * *"

[functions.shopify-get-shipping-rates]
verify_jwt = true
